// <auto-generated />
using System;
using Confera.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConferaDbContext))]
    [Migration("20260916141437_RoomVersion")]
    partial class RoomVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confera.Domain.Bookings.BookedRoomServiceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ServicePriceSnapshot")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("PK_BookedRoomServiceSnapshots");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_BookedRoomServiceSnapshots_BookingId");

                    b.ToTable("BookedRoomServiceSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookedRoomServiceSnapshots_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BookedRoomServiceSnapshots_ServiceNameSnapshot", "confera_utf16_length(\"ServiceNameSnapshot\") <= 64 AND confera_name_key(\"ServiceNameSnapshot\") <> ''");

                            t.HasCheckConstraint("CK_BookedRoomServiceSnapshots_ServicePriceSnapshot", "\"ServicePriceSnapshot\" BETWEEN 200 AND 20000 AND \"ServicePriceSnapshot\" = round(\"ServicePriceSnapshot\", 3)");
                        });
                });

            modelBuilder.Entity("Confera.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<decimal>("HourlyRateSnapshot")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("PK_Bookings");

                    b.HasIndex("RoomId", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("IX_Bookings_RoomPeriod");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_CreatedAtUtc", "isfinite(\"CreatedAtUtc\") AND \"CreatedAtUtc\" BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");

                            t.HasCheckConstraint("CK_Bookings_Duration", "\"EndsAtUtc\" - \"StartsAtUtc\" BETWEEN INTERVAL '30 minutes' AND INTERVAL '24 hours'");

                            t.HasCheckConstraint("CK_Bookings_EndsAtUtc", "isfinite(\"EndsAtUtc\") AND \"EndsAtUtc\" BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");

                            t.HasCheckConstraint("CK_Bookings_HourlyRateSnapshot", "\"HourlyRateSnapshot\" BETWEEN 1000 AND 100000 AND \"HourlyRateSnapshot\" = round(\"HourlyRateSnapshot\", 3)");

                            t.HasCheckConstraint("CK_Bookings_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_Bookings_StartsAtUtc", "isfinite(\"StartsAtUtc\") AND \"StartsAtUtc\" BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");

                            t.HasCheckConstraint("CK_Bookings_TotalPrice", "\"TotalPrice\" BETWEEN 0 AND 999999999999999.999 AND \"TotalPrice\" = round(\"TotalPrice\", 3)");
                        });
                });

            modelBuilder.Entity("Confera.Domain.Bookings.BookingPriceSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<decimal>("HourlyRateSnapshot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MultiplierSnapshot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PricingCodeSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp(6) with time zone");

                    b.HasKey("Id")
                        .HasName("PK_BookingPriceSegments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_BookingPriceSegments_BookingId");

                    b.ToTable("BookingPriceSegments", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingPriceSegments_Duration", "\"EndsAtUtc\" > \"StartsAtUtc\"");

                            t.HasCheckConstraint("CK_BookingPriceSegments_EndsAtUtc", "isfinite(\"EndsAtUtc\") AND \"EndsAtUtc\" BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");

                            t.HasCheckConstraint("CK_BookingPriceSegments_HourlyRateSnapshot", "\"HourlyRateSnapshot\" BETWEEN 1000 AND 100000 AND \"HourlyRateSnapshot\" = round(\"HourlyRateSnapshot\", 3)");

                            t.HasCheckConstraint("CK_BookingPriceSegments_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BookingPriceSegments_MultiplierSnapshot", "\"MultiplierSnapshot\" BETWEEN 0.50 AND 2.00 AND \"MultiplierSnapshot\" = round(\"MultiplierSnapshot\", 2)");

                            t.HasCheckConstraint("CK_BookingPriceSegments_Price", "\"Price\" BETWEEN 0 AND 4800000 AND \"Price\" = round(\"Price\", 3)");

                            t.HasCheckConstraint("CK_BookingPriceSegments_PricingCodeSnapshot", "confera_utf16_length(\"PricingCodeSnapshot\") <= 64 AND confera_name_key(\"PricingCodeSnapshot\") <> ''");

                            t.HasCheckConstraint("CK_BookingPriceSegments_StartsAtUtc", "isfinite(\"StartsAtUtc\") AND \"StartsAtUtc\" BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");
                        });
                });

            modelBuilder.Entity("Confera.Domain.Bookings.BookingPricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time(6) without time zone");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time(6) without time zone");

                    b.HasKey("Id")
                        .HasName("PK_BookingPricingRules");

                    b.HasAlternateKey("Priority")
                        .HasName("UQ_BookingPricingRules_Priority");

                    b.ToTable("BookingPricingRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingPricingRules_Code", "confera_utf16_length(\"Code\") <= 64 AND confera_name_key(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_BookingPricingRules_DailyInterval", "\"StartsAt\" >= TIME '00:00' AND \"StartsAt\" < TIME '24:00' AND \"EndsAt\" >= TIME '00:00' AND \"EndsAt\" < TIME '24:00' AND \"StartsAt\" <> \"EndsAt\"");

                            t.HasCheckConstraint("CK_BookingPricingRules_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_BookingPricingRules_Multiplier", "\"Multiplier\" BETWEEN 0.50 AND 2.00 AND \"Multiplier\" = round(\"Multiplier\", 2)");

                            t.HasCheckConstraint("CK_BookingPricingRules_Name", "confera_utf16_length(\"Name\") <= 64 AND confera_name_key(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("Confera.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("confera_name_key(\"Name\")", true)
                        .UseCollation("C");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id")
                        .HasName("PK_Rooms");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Rooms_ActiveName")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_Capacity", "\"Capacity\" > 0");

                            t.HasCheckConstraint("CK_Rooms_HourlyRate", "\"HourlyRate\" BETWEEN 1000 AND 100000 AND \"HourlyRate\" = round(\"HourlyRate\", 3)");

                            t.HasCheckConstraint("CK_Rooms_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_Rooms_Name", "confera_utf16_length(\"Name\") <= 64 AND confera_name_key(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_Rooms_Version", "\"Version\" <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Confera.Domain.Rooms.RoomService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("confera_name_key(\"Name\")", true)
                        .UseCollation("C");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_RoomServices");

                    b.HasIndex("RoomId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("UX_RoomServices_RoomName");

                    b.ToTable("RoomServices", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoomServices_Id", "\"Id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_RoomServices_Name", "confera_utf16_length(\"Name\") <= 64 AND confera_name_key(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_RoomServices_Price", "\"Price\" BETWEEN 200 AND 20000 AND \"Price\" = round(\"Price\", 3)");
                        });
                });

            modelBuilder.Entity("Confera.Infrastructure.Persistence.InitializationMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp(6) with time zone");

                    b.HasKey("Key")
                        .HasName("PK_InitializationMarkers");

                    b.ToTable("InitializationMarkers", null, t =>
                        {
                            t.HasCheckConstraint("CK_InitializationMarkers_CompletedAtUtc", "isfinite(\"CompletedAtUtc\") AND \"CompletedAtUtc\" BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");

                            t.HasCheckConstraint("CK_InitializationMarkers_Key", "confera_utf16_length(\"Key\") <= 64 AND confera_name_key(\"Key\") <> ''");
                        });
                });

            modelBuilder.Entity("Confera.Domain.Bookings.BookedRoomServiceSnapshot", b =>
                {
                    b.HasOne("Confera.Domain.Bookings.Booking", null)
                        .WithMany("Services")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookedRoomServiceSnapshots_Bookings");
                });

            modelBuilder.Entity("Confera.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Confera.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Rooms");
                });

            modelBuilder.Entity("Confera.Domain.Bookings.BookingPriceSegment", b =>
                {
                    b.HasOne("Confera.Domain.Bookings.Booking", null)
                        .WithMany("PriceSegments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingPriceSegments_Bookings");
                });

            modelBuilder.Entity("Confera.Domain.Rooms.RoomService", b =>
                {
                    b.HasOne("Confera.Domain.Rooms.Room", null)
                        .WithMany("Services")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomServices_Rooms");
                });

            modelBuilder.Entity("Confera.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("PriceSegments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Confera.Domain.Rooms.Room", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
