<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <RuntimeHostConfigurationOption Include="Npgsql.DisableDateTimeInfinityConversions" Value="true" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Confera.Testing" />
    <Compile Include="../Shared/PostgresFixture.cs" Link="Fixtures/PostgresFixture.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Confera.Api\Confera.Api.csproj" />
    <ProjectReference Include="..\..\src\Confera.Application\Confera.Application.csproj" />
    <ProjectReference Include="..\..\src\Confera.Domain\Confera.Domain.csproj" />
    <ProjectReference Include="..\..\src\Confera.Infrastructure\Confera.Infrastructure.csproj" />
  </ItemGroup>

</Project>
