<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
    <UserSecretsId>1191f065-3e23-452b-8880-3fe5eb631a88</UserSecretsId>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <RuntimeHostConfigurationOption Include="Npgsql.DisableDateTimeInfinityConversions" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\orchestration\Confera.ServiceDefaults\Confera.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Confera.Application\Confera.Application.csproj" />
    <ProjectReference Include="..\Confera.Infrastructure\Confera.Infrastructure.csproj" />
  </ItemGroup>

</Project>
